//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciTakip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretmenUzmanlik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgretmenUzmanlik()
        {
            this.SinifUzmanlik = new HashSet<SinifUzmanlik>();
        }
    
        public int OgretmenUzmanlikID { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public Nullable<int> UzmanlikID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Ogretmen Ogretmen { get; set; }
        public virtual Uzmanlik Uzmanlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinifUzmanlik> SinifUzmanlik { get; set; }
    }
}
