//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciTakip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinifUzmanlik
    {
        public int SinifUzmanlikID { get; set; }
        public Nullable<int> OgretmenUzmanlikID { get; set; }
        public Nullable<int> SinifID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual OgretmenUzmanlik OgretmenUzmanlik { get; set; }
        public virtual Sinif Sinif { get; set; }
    }
}
